// <auto-generated />
using System;
using FinalProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinalProject.Migrations
{
    [DbContext(typeof(FinancialDbContext))]
    partial class FinancialDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinalProject.Models.Derivative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("RiskFreeRate")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("StrikePrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UnderlyingId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UnderlyingId");

                    b.ToTable("Derivatives");
                });

            modelBuilder.Entity("FinalProject.Models.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DerivativeId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TradeDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DerivativeId");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("FinalProject.Models.Underlying", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Volatility")
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("Id");

                    b.ToTable("Underlyings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Apple Inc.",
                            CurrentPrice = 150.00m,
                            Symbol = "AAPL",
                            Volatility = 0.25m
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Tesla Inc.",
                            CurrentPrice = 200.00m,
                            Symbol = "TSLA",
                            Volatility = 0.45m
                        });
                });

            modelBuilder.Entity("FinalProject.Models.Derivative", b =>
                {
                    b.HasOne("FinalProject.Models.Underlying", "Underlying")
                        .WithMany("Derivatives")
                        .HasForeignKey("UnderlyingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Underlying");
                });

            modelBuilder.Entity("FinalProject.Models.Trade", b =>
                {
                    b.HasOne("FinalProject.Models.Derivative", "Derivative")
                        .WithMany("Trades")
                        .HasForeignKey("DerivativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Derivative");
                });

            modelBuilder.Entity("FinalProject.Models.Derivative", b =>
                {
                    b.Navigation("Trades");
                });

            modelBuilder.Entity("FinalProject.Models.Underlying", b =>
                {
                    b.Navigation("Derivatives");
                });
#pragma warning restore 612, 618
        }
    }
}
